### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by glowkeeper** [minima-global/Minima#18]
Please open MiniDapps with a Fullscreen, since that's how they're being designed.

**Comment by eurobuddha** [comment]
Built-in Fullscreen Mode in Chrome for Android

Alternatively, any AppStudio web app can run in fullscreen mode on Chrome for Android by opening the app in the browser, then:

Tapping the Menu button (three vertical dots) in the upper right-hand corner of the screen (or tap the hardware menu button on those devices having one)
Selecting Add to homescreen from the menu
Tapping the Add button in the pop up dialog
Then, from the home screen, tap the app icon to open in fullscreen mode.
This is a newer Chrome feature than the first method described above and is typically the preferable option.

I have tried this and when opening the minihub we are still a little too wide. Minihub is due a reskin so i will close this issue here as it will be resolved in the new minihub to be released.

**Comment by eurobuddha** [comment]
fixed in 98.15
