### ISSUE TITLE
Wallet > Send: Form is cleared after cancelling send

### ISSUE THREAD

**Issue by MiniJaz** [minima-global/Minima#265]
Hi,

Issue Impact: Minor
Device Manufacturer: Samsung
Device Model: S10
Device OS: Android
Device OS Version: 11
Application Version: apk: v0.98.24 wallet version 1.1.2

What Happened?: I entered tx details into the Send form, clicked on Send Funds but then wanted to change the amount so clicked cancel, the form was cleared completely and defaulted back to Minima resulting in having to recomplete the form from scratch.

What Did You Expect To Happen? The form would remain completed so minor changes could be made

Steps to recreate: 
1 Complete tx details
2. Click Send Funds
3. Click Cancel 

![SendForm](https://user-images.githubusercontent.com/60537663/121366089-19e5c080-c931-11eb-8788-14e42cc2eb3e.jpg)
![ClearedForm](https://user-images.githubusercontent.com/60537663/121366096-1baf8400-c931-11eb-9462-9756a54357e6.jpg)

Thanks!

**Comment by eurobuddha** [comment]
this bug is not just from cancelling send, if you are staging a txn and during that time you get a balance change in the node the popup in the wallet clears the address fireld and you have to start from scratch. Super annoying bug especially when your node is pumping away in the background running 3 different power console tasks. this is more than a low bug its a Minor imho

**Comment by jazminrib** [comment]
> this bug is not just from cancelling send, if you are staging a txn and during that time you get a balance change in the node the popup in the wallet clears the address fireld and you have to start from scratch. Super annoying bug especially when your node is pumping away in the background running 3 different power console tasks. this is more than a low bug its a Minor imho

This is logged in ticket #244
