### ISSUE TITLE
Storefront navigation blocked by tab pop-up

### ISSUE THREAD

**Issue by lewisc5** [minima-global/Minima#278]
I'm not sure if this happens for everyone, or is more unique to my device (Motorola Moto G Fast), but Chrome pops up a little bar on the bottom so I can navigate between tabs, but that completely covers the navigation tab on the bottom of Storefront. I didn't even know there was a button to get back to Storefronts or show All MiniDapps at the bottom until I connected via my desktop.

![Screenshot_20210611-165613](https://user-images.githubusercontent.com/85313270/121748238-9d8ce200-cad6-11eb-96fd-685353ec71d3.png)

**Comment by glowkeeper** [comment]
This is because of Chrome's newish bottom tab-bar on Android, which takes a bit of getting used to - you just need to hold your thumb on the screen and gently swipe up, as that makes both the URL search bar and bottom tab bar disappear. So no need to resort to the desktop.

I'm not certain there's much we can do about this as it's a _feature_ of Chrome, rather than a _bug_ with Storefront, but I will investigate. Meanwhile, a quick read around various forums tells me that most people are getting used to how that bottom bar works and are aware of how to make sites they visit full screen.

**Comment by lewisc5** [comment]
perhaps the navigation buttons on the bottom could be moved to somewhere on the top or top left instead?

**Comment by glowkeeper** [comment]
I'm hoping most are becoming used to that bottom tab bar and what needs to be done to make sites fullscreen. Meanwhile, I'll investigate and see if there's a fix - I'd like to avoid a redesign, if possible.
